-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 10:58:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ipiresies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ipiresies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ipiresies` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ipiresies` ;

-- -----------------------------------------------------
-- Table `ipiresies`.`audits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`audits` (
  `auditid` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NULL DEFAULT NULL,
  `first_nameid` INT NULL DEFAULT NULL,
  `first_dateid` DATE NULL DEFAULT NULL,
  `second_nameid` INT NULL DEFAULT NULL,
  `second_dateid` DATE NULL DEFAULT NULL,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `action_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`auditid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`ranki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`ranki` (
  `rankid` INT NOT NULL,
  `num_of_duty` INT NULL DEFAULT NULL,
  `rankName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`rankid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`names` (
  `nameid` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `AFM` BIGINT NULL DEFAULT NULL,
  `rankid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`nameid`),
  INDEX `rankid_idx` (`rankid` ASC) VISIBLE,
  INDEX `rankidFROMNAME_idx` (`rankid` ASC) VISIBLE,
  CONSTRAINT `rankidFROMNAME`
    FOREIGN KEY (`rankid`)
    REFERENCES `ipiresies`.`ranki` (`rankid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`date` (
  `dateid` DATE NOT NULL,
  `argeia` INT NULL DEFAULT NULL,
  `sk` INT NULL DEFAULT NULL,
  PRIMARY KEY (`dateid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`availability` (
  `availabilityid` INT NOT NULL AUTO_INCREMENT,
  `nameid` INT NOT NULL,
  `dateid` DATE NOT NULL,
  `mode` ENUM('green', 'red') NOT NULL DEFAULT 'green',
  PRIMARY KEY (`availabilityid`),
  UNIQUE INDEX `nameid_dateid_unique` (`nameid` ASC, `dateid` ASC) VISIBLE,
  INDEX `dateid` (`dateid` ASC) VISIBLE,
  CONSTRAINT `availability_ibfk_1`
    FOREIGN KEY (`nameid`)
    REFERENCES `ipiresies`.`names` (`nameid`),
  CONSTRAINT `availability_ibfk_2`
    FOREIGN KEY (`dateid`)
    REFERENCES `ipiresies`.`date` (`dateid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`post` (
  `postid` INT NOT NULL,
  `eas` INT NULL DEFAULT NULL,
  `aydm` INT NULL DEFAULT NULL,
  `baydm` INT NULL DEFAULT NULL,
  `apil` INT NULL DEFAULT NULL,
  `na` INT NULL DEFAULT NULL,
  PRIMARY KEY (`postid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`ipiresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`ipiresia` (
  `ipiresiaid` INT NOT NULL AUTO_INCREMENT,
  `rankid` INT NULL DEFAULT NULL,
  `dateid` DATE NULL DEFAULT NULL,
  `postid` INT NULL DEFAULT NULL,
  `nameid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ipiresiaid`),
  INDEX `rankid_idx` (`rankid` ASC) VISIBLE,
  INDEX `dateid_idx` (`dateid` ASC) VISIBLE,
  INDEX `postid_idx` (`postid` ASC) VISIBLE,
  INDEX `nameid_idx` (`nameid` ASC) VISIBLE,
  CONSTRAINT `dateid`
    FOREIGN KEY (`dateid`)
    REFERENCES `ipiresies`.`date` (`dateid`),
  CONSTRAINT `nameid`
    FOREIGN KEY (`nameid`)
    REFERENCES `ipiresies`.`names` (`nameid`),
  CONSTRAINT `postid`
    FOREIGN KEY (`postid`)
    REFERENCES `ipiresies`.`post` (`postid`),
  CONSTRAINT `rankid`
    FOREIGN KEY (`rankid`)
    REFERENCES `ipiresies`.`ranki` (`rankid`))
ENGINE = InnoDB
AUTO_INCREMENT = 1054
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`serves_on`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`serves_on` (
  `counter` INT NOT NULL AUTO_INCREMENT,
  `postid` INT NOT NULL,
  `nameid` INT NOT NULL,
  PRIMARY KEY (`counter`),
  INDEX `postid_idx` (`postid` ASC) VISIBLE,
  INDEX `nameIDI_idx` (`nameid` ASC) VISIBLE,
  CONSTRAINT `nameIDI`
    FOREIGN KEY (`nameid`)
    REFERENCES `ipiresies`.`names` (`nameid`),
  CONSTRAINT `postIDI`
    FOREIGN KEY (`postid`)
    REFERENCES `ipiresies`.`post` (`postid`))
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ipiresies`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`users` (
  `userid` INT NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(200) NULL DEFAULT NULL,
  `priviledges` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `ipiresies` ;

-- -----------------------------------------------------
-- Placeholder table for view `ipiresies`.`triemerousdays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ipiresies`.`triemerousdays` (`start_date` INT, `middle_date` INT, `end_date` INT);

-- -----------------------------------------------------
-- procedure insert_dates
-- -----------------------------------------------------

DELIMITER $$
USE `ipiresies`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_dates`()
BEGIN
    DECLARE currentDate DATE;
    DECLARE endDate DATE;
    DECLARE sk INT DEFAULT 0;
    DECLARE argeia INT DEFAULT 0;

    SET currentDate = '2024-08-01';
    SET endDate = '2024-12-31';

    WHILE currentDate <= endDate DO
        -- Έλεγχος αν η ημερομηνία είναι Σάββατο (7) ή Κυριακή (1)
        SET sk = CASE WHEN DAYOFWEEK(currentDate) IN (1, 7) THEN 1 ELSE 0 END;

        -- Έλεγχος αν η ημερομηνία είναι αργία
        SET argeia = CASE WHEN EXISTS (SELECT 1 FROM holidays WHERE dateid = currentDate) THEN 1 ELSE 0 END;

        -- Εισαγωγή της ημερομηνίας στον πίνακα
        INSERT INTO `date` (dateid, argeia, sk)
        VALUES (currentDate, argeia, sk)
        ON DUPLICATE KEY UPDATE argeia = VALUES(argeia), sk = VALUES(sk);

        -- Μετάβαση στην επόμενη ημέρα
        SET currentDate = DATE_ADD(currentDate, INTERVAL 1 DAY);
    END WHILE;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `ipiresies`.`triemerousdays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ipiresies`.`triemerousdays`;
USE `ipiresies`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ipiresies`.`triemerousdays` AS select `d1`.`dateid` AS `start_date`,`d2`.`dateid` AS `middle_date`,`d3`.`dateid` AS `end_date` from ((`ipiresies`.`date` `d1` join `ipiresies`.`date` `d2` on((`d2`.`dateid` = (`d1`.`dateid` + interval 1 day)))) join `ipiresies`.`date` `d3` on((`d3`.`dateid` = (`d1`.`dateid` + interval 2 day)))) where ((`d1`.`argeia` = 1) and (`d2`.`argeia` = 1) and (`d3`.`argeia` = 1));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
